name: multiview_chemvae
channels:
  - conda-forge
  - rdkit
dependencies:
  - python=3.6
  - ipykernel
  - nltk
  - tensorflow=1.15
  - rdkit
  - matplotlib
  - numpy=1.19
  - pandas
  - pip
  - scikit-learn
  - h5py=2.10.0
  - pip:
    - keras==2.3.1
    - git+https://github.com/bp-kelley/descriptastorus